import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";

export default function Question3() {
  const navigate = useNavigate();

  const [swapped, setSwapped] = useState(false);

  const suppressClickUntil = useRef(0);

  const swapButtons = () => {
    setSwapped((previous) => !previous);

    // Suppress any click generated by this touch/pointer.
    suppressClickUntil.current =
      Date.now() + 800;
  };

  const handleYes = () => {
    // Ignore the click that can be generated
    // after touching No.
    if (
      Date.now() <
      suppressClickUntil.current
    ) {
      return;
    }

    navigate("/answer");
  };

  const handleNoPointerDown = (
    event: React.PointerEvent<HTMLButtonElement>
  ) => {
    if (event.pointerType === "touch") {
      event.preventDefault();

      swapButtons();
    }
  };

  const handleNoPointerEnter = (
    event: React.PointerEvent<HTMLButtonElement>
  ) => {
    if (event.pointerType === "mouse") {
      swapButtons();
    }
  };

  const handleNoClick = (
    event: React.MouseEvent<HTMLButtonElement>
  ) => {
    /*
     * On mobile, prevent the synthetic click
     * produced after a touch/long press.
     */
    if (Date.now() < suppressClickUntil.current) {
      event.preventDefault();
      event.stopPropagation();
    }
  };

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        width: "100vw",
        height: "100dvh",
        minHeight: "100dvh",
        background: "#f6f5f2",
        color: "#151515",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily:
          "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
        overflow: "hidden",
        userSelect: "none",
        padding: 24,
        boxSizing: "border-box",
      }}
    >
      {/* Decorative circle */}
      <div
        style={{
          position: "absolute",
          width: 320,
          height: 320,
          borderRadius: "50%",
          border:
            "1px solid rgba(0,0,0,0.06)",
          top: -150,
          right: -100,
          pointerEvents: "none",
        }}
      />

      {/* Decorative circle */}
      <div
        style={{
          position: "absolute",
          width: 420,
          height: 420,
          borderRadius: "50%",
          border:
            "1px solid rgba(0,0,0,0.05)",
          bottom: -250,
          left: -180,
          pointerEvents: "none",
        }}
      />

      <main
        style={{
          position: "relative",
          width: "100%",
          maxWidth: 700,
          textAlign: "center",
        }}
      >
        {/* Question number */}
        <p
          style={{
            margin: "0 0 18px",
            fontSize: 12,
            letterSpacing: "3px",
            textTransform: "uppercase",
            color: "#999",
          }}
        >
          Question 03
        </p>

        {/* Question */}
        <h1
          style={{
            margin: "0 auto 40px",
            fontSize:
              "clamp(36px, 7vw, 58px)",
            lineHeight: 1.08,
            fontWeight: 500,
            letterSpacing: "-2px",
          }}
        >
          Are you{" "}
          <span
            style={{
              fontFamily: "Georgia, serif",
              fontStyle: "italic",
              fontWeight: 400,
            }}
          >
            CZ head?
          </span>
        </h1>

        {/* Buttons */}
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            gap: 14,
            minHeight: 52,
          }}
        >
          {!swapped ? (
            <>
              {/* YES */}
              <button
                type="button"
                onClick={handleYes}
                style={buttonStyle}
              >
                Yes
              </button>

              {/* NO */}
              <button
                type="button"
                onPointerEnter={
                  handleNoPointerEnter
                }
                onPointerDown={
                  handleNoPointerDown
                }
                onClick={handleNoClick}
                style={buttonStyle}
              >
                No
              </button>
            </>
          ) : (
            <>
              {/* NO */}
              <button
                type="button"
                onPointerEnter={
                  handleNoPointerEnter
                }
                onPointerDown={
                  handleNoPointerDown
                }
                onClick={handleNoClick}
                style={buttonStyle}
              >
                No
              </button>

              {/* YES */}
              <button
                type="button"
                onClick={handleYes}
                style={buttonStyle}
              >
                Yes
              </button>
            </>
          )}
        </div>
      </main>
    </div>
  );
}

const buttonStyle: React.CSSProperties = {
  width: 105,
  height: 48,
  border: "1px solid #222",
  borderRadius: 12,
  background: "transparent",
  color: "#111",
  fontSize: 15,
  fontWeight: 500,
  letterSpacing: "0.5px",
  cursor: "pointer",
  touchAction: "manipulation",
  WebkitTapHighlightColor: "transparent",
  userSelect: "none",
};